// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_link

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LinkResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"auto_gen_config_default_vrf": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto-generate configuration on default VRF. If enabled, automatically generate default VRF configuration over the physical or port-channel interface for a border device in an easy fabric.",
				MarkdownDescription: "Auto-generate configuration on default VRF. If enabled, automatically generate default VRF configuration over the physical or port-channel interface for a border device in an easy fabric.",
				Default:             booldefault.StaticBool(false),
			},
			"auto_gen_config_nx_peer_default_vrf": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto-generate configuration for NX-OS/IOS XE Peer on default VRF. If enabled, automatically generate Default VRF (Global VRF for IOS XE) configuration for managed neighbor devices.",
				MarkdownDescription: "Auto-generate configuration for NX-OS/IOS XE Peer on default VRF. If enabled, automatically generate Default VRF (Global VRF for IOS XE) configuration for managed neighbor devices.",
				Default:             booldefault.StaticBool(false),
			},
			"auto_gen_config_peer": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto-generate configuration for the peer. If enabled, automatically generate VRF Lite configuration for managed NX-OS neighbor devices.",
				MarkdownDescription: "Auto-generate configuration for the peer. If enabled, automatically generate VRF Lite configuration for managed NX-OS neighbor devices.",
				Default:             booldefault.StaticBool(false),
			},
			"bfd_echo_on_dst_interface": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disable BFD Echo on the destination interface. Applicable only when BFD is enabled in the fabric.",
				MarkdownDescription: "Disable BFD Echo on the destination interface. Applicable only when BFD is enabled in the fabric.",
				Default:             booldefault.StaticBool(false),
			},
			"bfd_echo_on_src_interface": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disable BFD Echo on the source interface. Applicable only when BFD is enabled in the fabric.",
				MarkdownDescription: "Disable BFD Echo on the source interface. Applicable only when BFD is enabled in the fabric.",
				Default:             booldefault.StaticBool(false),
			},
			"bpdu_guard": schema.StringAttribute{
				Optional:            true,
				Description:         "BPDU guard for spanning-tree.",
				MarkdownDescription: "BPDU guard for spanning-tree.",
			},
			"dci_tracking": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable DCI tracking on the physical interface on the easy fabric side of this link, if the switch is any type of border gateway.",
				MarkdownDescription: "Enable DCI tracking on the physical interface on the easy fabric side of this link, if the switch is any type of border gateway.",
				Default:             booldefault.StaticBool(false),
			},
			"dci_tracking_enable_flag": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "DCI tracking enable flag to deploy DCI tracking.",
				MarkdownDescription: "DCI tracking enable flag to deploy DCI tracking.",
				Default:             booldefault.StaticBool(false),
			},
			"default_vrf_ebgp_neighbor_password": schema.StringAttribute{
				Optional:            true,
				Description:         "Default VRF BGP neighbor password.",
				MarkdownDescription: "Default VRF BGP neighbor password.",
			},
			"dhcp_relay_on_dst_interface": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable DHCP relay on the destination interface.",
				MarkdownDescription: "Enable DHCP relay on the destination interface.",
				Default:             booldefault.StaticBool(false),
			},
			"dhcp_relay_on_src_interface": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable DHCP relay on the source interface.",
				MarkdownDescription: "Enable DHCP relay on the source interface.",
				Default:             booldefault.StaticBool(false),
			},
			"dst_cluster_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Name of the destination cluster.",
				MarkdownDescription: "Name of the destination cluster.",
			},
			"dst_ebgp_asn": schema.StringAttribute{
				Optional:            true,
				Description:         "BGP autonomous system number in the destination fabric.",
				MarkdownDescription: "BGP autonomous system number in the destination fabric.",
			},
			"dst_fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the destination fabric.",
				MarkdownDescription: "Name of the destination fabric.",
			},
			"dst_interface_config": schema.StringAttribute{
				Optional:            true,
				Description:         "Destination interface freeform configuration. All configurations should strictly match 'show run' output, with respect to case and newlines. Any mismatches will yield unexpected diffs during deployment.",
				MarkdownDescription: "Destination interface freeform configuration. All configurations should strictly match 'show run' output, with respect to case and newlines. Any mismatches will yield unexpected diffs during deployment.",
			},
			"dst_interface_description": schema.StringAttribute{
				Optional:            true,
				Description:         "Description for the destination interface.",
				MarkdownDescription: "Description for the destination interface.",
			},
			"dst_interface_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the destination interface.",
				MarkdownDescription: "Name of the destination interface.",
			},
			"dst_ip": schema.StringAttribute{
				Optional:            true,
				Description:         "IP address of the destination interface.",
				MarkdownDescription: "IP address of the destination interface.",
			},
			"dst_ip_address": schema.StringAttribute{
				Optional:            true,
				Description:         "Destination IP address.",
				MarkdownDescription: "Destination IP address.",
			},
			"dst_ip_address_mask": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv4 address with mask of the destination interface.",
				MarkdownDescription: "IPv4 address with mask of the destination interface.",
			},
			"dst_ipv6": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv6 address of the destination interface.",
				MarkdownDescription: "IPv6 address of the destination interface.",
			},
			"dst_ipv6_address": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv6 address of the destination interface.",
				MarkdownDescription: "IPv6 address of the destination interface.",
			},
			"dst_ipv6_address_mask": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv6 address with mask of the destination interface.",
				MarkdownDescription: "IPv6 address with mask of the destination interface.",
			},
			"dst_kme_server_ip": schema.StringAttribute{
				Optional:            true,
				Description:         "Destination KME server IP. Key Management Entity server IPv4 address.",
				MarkdownDescription: "Destination KME server IP. Key Management Entity server IPv4 address.",
			},
			"dst_macsec_key_chain_prefix": schema.StringAttribute{
				Optional:            true,
				Description:         "Destination MACsec policy/key-chain name prefix. This prefix is used to form policy and key-chain names for MACsec configuration at the destination.",
				MarkdownDescription: "Destination MACsec policy/key-chain name prefix. This prefix is used to form policy and key-chain names for MACsec configuration at the destination.",
			},
			"dst_netflow_monitor_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Layer 3 Monitor Name to be applied to the destination interface.",
				MarkdownDescription: "Layer 3 Monitor Name to be applied to the destination interface.",
			},
			"dst_qkd_profile_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Destination QKD profile name.",
				MarkdownDescription: "Destination QKD profile name.",
			},
			"dst_switch_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Unique identifier of the destination switch.",
				MarkdownDescription: "Unique identifier of the destination switch.",
			},
			"dst_switch_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the destination device.",
				MarkdownDescription: "Name of the destination device.",
			},
			"dst_trustpoint_label": schema.StringAttribute{
				Optional:            true,
				Description:         "Destination trust point label. TLS authentication type trustpoint label.",
				MarkdownDescription: "Destination trust point label. TLS authentication type trustpoint label.",
			},
			"dst_vrf_name": schema.StringAttribute{
				Optional:            true,
				Description:         "VRF name in the destination fabric, default VRF if not specified.",
				MarkdownDescription: "VRF name in the destination fabric, default VRF if not specified.",
			},
			"ebgp_auth_key_encryption_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "BGP key encryption type: 3 - 3DES, 6 - Cisco type 6, 7 - Cisco type 7",
				MarkdownDescription: "BGP key encryption type: 3 - 3DES, 6 - Cisco type 6, 7 - Cisco type 7",
				Default:             stringdefault.StaticString("3des"),
			},
			"ebgp_bfd": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable BGP BFD.",
				MarkdownDescription: "Enable BGP BFD.",
				Default:             booldefault.StaticBool(false),
			},
			"ebgp_log_neighbor_change": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable BGP log neighbor change.",
				MarkdownDescription: "Enable BGP log neighbor change.",
				Default:             booldefault.StaticBool(false),
			},
			"ebgp_maximum_paths": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "BGP maximum paths.",
				MarkdownDescription: "BGP maximum paths.",
				Default:             int64default.StaticInt64(64),
			},
			"ebgp_multihop": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "eBGP time-to-live value for the remote peer.",
				MarkdownDescription: "eBGP time-to-live value for the remote peer.",
				Default:             int64default.StaticInt64(5),
			},
			"ebgp_password": schema.StringAttribute{
				Optional:            true,
				Description:         "Encrypted eBGP password hex string.",
				MarkdownDescription: "Encrypted eBGP password hex string.",
			},
			"ebgp_send_comboth": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable BGP send-community both.",
				MarkdownDescription: "Enable BGP send-community both.",
				Default:             booldefault.StaticBool(false),
			},
			"enable_ebgp_password": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable eBGP password.",
				MarkdownDescription: "Enable eBGP password.",
				Default:             booldefault.StaticBool(false),
			},
			"fec": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Forward Error Correction (FEC) mode",
				MarkdownDescription: "Forward Error Correction (FEC) mode",
				Default:             stringdefault.StaticString("auto"),
			},
			"ignore_certificate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Ignore certificate to skip verification of the incoming certificate.",
				MarkdownDescription: "Ignore certificate to skip verification of the incoming certificate.",
				Default:             booldefault.StaticBool(false),
			},
			"inherit_ebgp_password_msd_settings": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Inherit eBGP password from MSD settings. Applicable only when source and destination fabrics are in the same MSD fabric.",
				MarkdownDescription: "Inherit eBGP password from MSD settings. Applicable only when source and destination fabrics are in the same MSD fabric.",
				Default:             booldefault.StaticBool(true),
			},
			"inherit_ttag_fabric_setting": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable timestamp tagging (ttag/ttag-strip) for DCI interfaces when PTP is enabled in fabric settings.",
				MarkdownDescription: "Enable timestamp tagging (ttag/ttag-strip) for DCI interfaces when PTP is enabled in fabric settings.",
				Default:             booldefault.StaticBool(true),
			},
			"interface_admin_state": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Admin state of the interface.",
				MarkdownDescription: "Admin state of the interface.",
				Default:             booldefault.StaticBool(true),
			},
			"interface_vrf": schema.StringAttribute{
				Optional:            true,
				Description:         "Interface VRF name.",
				MarkdownDescription: "Interface VRF name.",
			},
			"ip_redirects": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disable IP redirects.",
				MarkdownDescription: "Disable IP redirects.",
				Default:             booldefault.StaticBool(false),
			},
			"ipv4_pim": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable IPv4 Protocol Independent Multicast.",
				MarkdownDescription: "Enable IPv4 Protocol Independent Multicast.",
				Default:             booldefault.StaticBool(false),
			},
			"ipv4_trm": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable IPv4 tenant routed multicast.",
				MarkdownDescription: "Enable IPv4 tenant routed multicast.",
				Default:             booldefault.StaticBool(false),
			},
			"ipv6_pim": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable IPv6 Protocol Independent Multicast.",
				MarkdownDescription: "Enable IPv6 Protocol Independent Multicast.",
				Default:             booldefault.StaticBool(false),
			},
			"ipv6_trm": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable IPv6 tenant routed multicast.",
				MarkdownDescription: "Enable IPv6 tenant routed multicast.",
				Default:             booldefault.StaticBool(false),
			},
			"link_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the link.",
				MarkdownDescription: "Unique identifier of the link.",
			},
			"link_mtu": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Interface MTU.",
				MarkdownDescription: "Interface MTU.",
				Default:             int64default.StaticInt64(9216),
			},
			"link_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Type of the link.",
				MarkdownDescription: "Type of the link.",
			},
			"macsec": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable MACsec on the link.",
				MarkdownDescription: "Enable MACsec on the link.",
				Default:             booldefault.StaticBool(false),
			},
			"macsec_cipher_suite": schema.StringAttribute{
				Optional:            true,
				Description:         "MACsec cipher suite.",
				MarkdownDescription: "MACsec cipher suite.",
			},
			"macsec_fallback_cryptographic_algorithm": schema.StringAttribute{
				Optional:            true,
				Description:         "MACsec fallback cryptographic algorithm. AES_128_CMAC or AES_256_CMAC.",
				MarkdownDescription: "MACsec fallback cryptographic algorithm. AES_128_CMAC or AES_256_CMAC.",
			},
			"macsec_fallback_key_string": schema.StringAttribute{
				Optional:            true,
				Description:         "MACsec fallback key string. Cisco Type 7 Encrypted Octet String.",
				MarkdownDescription: "MACsec fallback key string. Cisco Type 7 Encrypted Octet String.",
			},
			"macsec_primary_cryptographic_algorithm": schema.StringAttribute{
				Optional:            true,
				Description:         "MACsec primary cryptographic algorithm. AES_128_CMAC or AES_256_CMAC.",
				MarkdownDescription: "MACsec primary cryptographic algorithm. AES_128_CMAC or AES_256_CMAC.",
			},
			"macsec_primary_key_string": schema.StringAttribute{
				Optional:            true,
				Description:         "MACsec primary key string. Cisco Type 7 Encrypted Octet String.",
				MarkdownDescription: "MACsec primary key string. Cisco Type 7 Encrypted Octet String.",
			},
			"mtu": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Interface MTU.",
				MarkdownDescription: "Interface MTU.",
				Default:             int64default.StaticInt64(9216),
			},
			"mtu_type": schema.StringAttribute{
				Optional:            true,
				Description:         "MTU for the interface.",
				MarkdownDescription: "MTU for the interface.",
			},
			"native_vlan": schema.Int64Attribute{
				Optional:            true,
				Description:         "Set native VLAN for the interface.",
				MarkdownDescription: "Set native VLAN for the interface.",
			},
			"netflow_on_dst_interface": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable NetFlow on the destination interface.",
				MarkdownDescription: "Enable NetFlow on the destination interface.",
				Default:             booldefault.StaticBool(false),
			},
			"netflow_on_src_interface": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable NetFlow on the source interface.",
				MarkdownDescription: "Enable NetFlow on the source interface.",
				Default:             booldefault.StaticBool(false),
			},
			"override_fabric_macsec": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, uses local link-level MACsec settings. When false, settings are inherited from the Fabric Management settings",
				MarkdownDescription: "When true, uses local link-level MACsec settings. When false, settings are inherited from the Fabric Management settings",
				Default:             booldefault.StaticBool(false),
			},
			"policy_type": schema.StringAttribute{
				Required:            true,
				Description:         "The link policy type. Determines the set of applicable templateInputs fields.",
				MarkdownDescription: "The link policy type. Determines the set of applicable templateInputs fields.",
			},
			"port_type_fast": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable spanning-tree edge port behavior.",
				MarkdownDescription: "Enable spanning-tree edge port behavior.",
				Default:             booldefault.StaticBool(true),
			},
			"qkd": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable MACsec with QKD configuration.",
				MarkdownDescription: "Enable MACsec with QKD configuration.",
				Default:             booldefault.StaticBool(false),
			},
			"redistrib_ebgp_route_map_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Redistribute BGP route map name. Route-map used to redistribute BGP routes to IGP in default VRF. Applicable only for easy fabric.",
				MarkdownDescription: "Redistribute BGP route map name. Route-map used to redistribute BGP routes to IGP in default VRF. Applicable only for easy fabric.",
			},
			"redistribute_route_server": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable redistribute direct on the route server.",
				MarkdownDescription: "Enable redistribute direct on the route server.",
				Default:             booldefault.StaticBool(false),
			},
			"route_server_routing_tag": schema.StringAttribute{
				Optional:            true,
				Description:         "Routing tag associated with the route server IP for redistribute direct.",
				MarkdownDescription: "Routing tag associated with the route server IP for redistribute direct.",
			},
			"routing_tag": schema.StringAttribute{
				Optional:            true,
				Description:         "Routing tag associated with the interface IP for default VRF.",
				MarkdownDescription: "Routing tag associated with the interface IP for default VRF.",
			},
			"skip_config_generation": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Skip configuration generation for the Multisite overlay IFC when enabled",
				MarkdownDescription: "Skip configuration generation for the Multisite overlay IFC when enabled",
				Default:             booldefault.StaticBool(false),
			},
			"speed": schema.StringAttribute{
				Optional:            true,
				Description:         "Interface Speed",
				MarkdownDescription: "Interface Speed",
			},
			"src_cluster_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Name of the source cluster.",
				MarkdownDescription: "Name of the source cluster.",
			},
			"src_ebgp_asn": schema.StringAttribute{
				Optional:            true,
				Description:         "BGP autonomous system number in the source fabric.",
				MarkdownDescription: "BGP autonomous system number in the source fabric.",
			},
			"src_fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the source fabric.",
				MarkdownDescription: "Name of the source fabric.",
			},
			"src_interface_config": schema.StringAttribute{
				Optional:            true,
				Description:         "Source interface freeform configuration. All configurations should strictly match 'show run' output, with respect to case and newlines. Any mismatches will yield unexpected diffs during deployment.",
				MarkdownDescription: "Source interface freeform configuration. All configurations should strictly match 'show run' output, with respect to case and newlines. Any mismatches will yield unexpected diffs during deployment.",
			},
			"src_interface_description": schema.StringAttribute{
				Optional:            true,
				Description:         "Description for the source interface.",
				MarkdownDescription: "Description for the source interface.",
			},
			"src_interface_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the source interface.",
				MarkdownDescription: "Name of the source interface.",
			},
			"src_ip": schema.StringAttribute{
				Optional:            true,
				Description:         "IP address of the source interface.",
				MarkdownDescription: "IP address of the source interface.",
			},
			"src_ip_address": schema.StringAttribute{
				Optional:            true,
				Description:         "IP address for the sub-interface in each VRF in the source fabric.",
				MarkdownDescription: "IP address for the sub-interface in each VRF in the source fabric.",
			},
			"src_ip_address_mask": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv4 address with mask of the source interface.",
				MarkdownDescription: "IPv4 address with mask of the source interface.",
			},
			"src_ipv6": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv6 address of the source interface.",
				MarkdownDescription: "IPv6 address of the source interface.",
			},
			"src_ipv6_address_mask": schema.StringAttribute{
				Optional:            true,
				Description:         "IPv6 address with mask of the source interface.",
				MarkdownDescription: "IPv6 address with mask of the source interface.",
			},
			"src_kme_server_ip": schema.StringAttribute{
				Optional:            true,
				Description:         "Source KME server IP. Key Management Entity server IPv4 address.",
				MarkdownDescription: "Source KME server IP. Key Management Entity server IPv4 address.",
			},
			"src_macsec_key_chain_prefix": schema.StringAttribute{
				Optional:            true,
				Description:         "Source MACsec policy/key-chain name prefix. This prefix is used to form policy and key-chain names for MACsec configuration at the source.",
				MarkdownDescription: "Source MACsec policy/key-chain name prefix. This prefix is used to form policy and key-chain names for MACsec configuration at the source.",
			},
			"src_netflow_monitor_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Layer 3 Monitor Name to be applied to the source interface.",
				MarkdownDescription: "Layer 3 Monitor Name to be applied to the source interface.",
			},
			"src_qkd_profile_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Source QKD profile name.",
				MarkdownDescription: "Source QKD profile name.",
			},
			"src_switch_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Unique identifier of the source switch.",
				MarkdownDescription: "Unique identifier of the source switch.",
			},
			"src_switch_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the source device.",
				MarkdownDescription: "Name of the source device.",
			},
			"src_trustpoint_label": schema.StringAttribute{
				Optional:            true,
				Description:         "Source trust point label. TLS authentication type trustpoint label.",
				MarkdownDescription: "Source trust point label. TLS authentication type trustpoint label.",
			},
			"src_vrf_name": schema.StringAttribute{
				Optional:            true,
				Description:         "VRF name in the source fabric, default VRF if not specified.",
				MarkdownDescription: "VRF name in the source fabric, default VRF if not specified.",
			},
			"template_config_gen_peer": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Template for configuration generation on the peer. Python template for VRF Lite configuration on NX-OS peer in an external fabric.",
				MarkdownDescription: "Template for configuration generation on the peer. Python template for VRF Lite configuration on NX-OS peer in an external fabric.",
				Default:             stringdefault.StaticString("Ext_VRF_Lite_Jython"),
			},
			"template_name": schema.StringAttribute{
				Optional:            true,
				Description:         "Name of the user-defined template",
				MarkdownDescription: "Name of the user-defined template",
			},
			"trunk_allowed_vlans": schema.StringAttribute{
				Optional:            true,
				Description:         "Trunk allowed VLANs (Allowed values - 'none', 'all', or VLAN ranges (ex- 1-200,500-2000,3000)).",
				MarkdownDescription: "Trunk allowed VLANs (Allowed values - 'none', 'all', or VLAN ranges (ex- 1-200,500-2000,3000)).",
			},
			"vrf_name_nx_peer_switch": schema.StringAttribute{
				Optional:            true,
				Description:         "VRF name in NX-OS peer switch. This field is applied to the edge router when the link is between a border in easy fabric and an edge router in an external fabric. Default VRF is used when blank. The border device always uses default VRF.",
				MarkdownDescription: "VRF name in NX-OS peer switch. This field is applied to the edge router when the link is between a border in easy fabric and an edge router in an external fabric. Default VRF is used when blank. The border device always uses default VRF.",
			},
		},
	}
}

type LinkModel struct {
	AutoGenConfigDefaultVrf              types.Bool   `tfsdk:"auto_gen_config_default_vrf"`
	AutoGenConfigNxPeerDefaultVrf        types.Bool   `tfsdk:"auto_gen_config_nx_peer_default_vrf"`
	AutoGenConfigPeer                    types.Bool   `tfsdk:"auto_gen_config_peer"`
	BfdEchoOnDstInterface                types.Bool   `tfsdk:"bfd_echo_on_dst_interface"`
	BfdEchoOnSrcInterface                types.Bool   `tfsdk:"bfd_echo_on_src_interface"`
	BpduGuard                            types.String `tfsdk:"bpdu_guard"`
	DciTracking                          types.Bool   `tfsdk:"dci_tracking"`
	DciTrackingEnableFlag                types.Bool   `tfsdk:"dci_tracking_enable_flag"`
	DefaultVrfEbgpNeighborPassword       types.String `tfsdk:"default_vrf_ebgp_neighbor_password"`
	DhcpRelayOnDstInterface              types.Bool   `tfsdk:"dhcp_relay_on_dst_interface"`
	DhcpRelayOnSrcInterface              types.Bool   `tfsdk:"dhcp_relay_on_src_interface"`
	DstClusterName                       types.String `tfsdk:"dst_cluster_name"`
	DstEbgpAsn                           types.String `tfsdk:"dst_ebgp_asn"`
	DstFabricName                        types.String `tfsdk:"dst_fabric_name"`
	DstInterfaceConfig                   types.String `tfsdk:"dst_interface_config"`
	DstInterfaceDescription              types.String `tfsdk:"dst_interface_description"`
	DstInterfaceName                     types.String `tfsdk:"dst_interface_name"`
	DstIp                                types.String `tfsdk:"dst_ip"`
	DstIpAddress                         types.String `tfsdk:"dst_ip_address"`
	DstIpAddressMask                     types.String `tfsdk:"dst_ip_address_mask"`
	DstIpv6                              types.String `tfsdk:"dst_ipv6"`
	DstIpv6Address                       types.String `tfsdk:"dst_ipv6_address"`
	DstIpv6AddressMask                   types.String `tfsdk:"dst_ipv6_address_mask"`
	DstKmeServerIp                       types.String `tfsdk:"dst_kme_server_ip"`
	DstMacsecKeyChainPrefix              types.String `tfsdk:"dst_macsec_key_chain_prefix"`
	DstNetflowMonitorName                types.String `tfsdk:"dst_netflow_monitor_name"`
	DstQkdProfileName                    types.String `tfsdk:"dst_qkd_profile_name"`
	DstSwitchId                          types.String `tfsdk:"dst_switch_id"`
	DstSwitchName                        types.String `tfsdk:"dst_switch_name"`
	DstTrustpointLabel                   types.String `tfsdk:"dst_trustpoint_label"`
	DstVrfName                           types.String `tfsdk:"dst_vrf_name"`
	EbgpAuthKeyEncryptionType            types.String `tfsdk:"ebgp_auth_key_encryption_type"`
	EbgpBfd                              types.Bool   `tfsdk:"ebgp_bfd"`
	EbgpLogNeighborChange                types.Bool   `tfsdk:"ebgp_log_neighbor_change"`
	EbgpMaximumPaths                     types.Int64  `tfsdk:"ebgp_maximum_paths"`
	EbgpMultihop                         types.Int64  `tfsdk:"ebgp_multihop"`
	EbgpPassword                         types.String `tfsdk:"ebgp_password"`
	EbgpSendComboth                      types.Bool   `tfsdk:"ebgp_send_comboth"`
	EnableEbgpPassword                   types.Bool   `tfsdk:"enable_ebgp_password"`
	Fec                                  types.String `tfsdk:"fec"`
	IgnoreCertificate                    types.Bool   `tfsdk:"ignore_certificate"`
	InheritEbgpPasswordMsdSettings       types.Bool   `tfsdk:"inherit_ebgp_password_msd_settings"`
	InheritTtagFabricSetting             types.Bool   `tfsdk:"inherit_ttag_fabric_setting"`
	InterfaceAdminState                  types.Bool   `tfsdk:"interface_admin_state"`
	InterfaceVrf                         types.String `tfsdk:"interface_vrf"`
	IpRedirects                          types.Bool   `tfsdk:"ip_redirects"`
	Ipv4Pim                              types.Bool   `tfsdk:"ipv4_pim"`
	Ipv4Trm                              types.Bool   `tfsdk:"ipv4_trm"`
	Ipv6Pim                              types.Bool   `tfsdk:"ipv6_pim"`
	Ipv6Trm                              types.Bool   `tfsdk:"ipv6_trm"`
	LinkId                               types.String `tfsdk:"link_id"`
	LinkMtu                              types.Int64  `tfsdk:"link_mtu"`
	LinkType                             types.String `tfsdk:"link_type"`
	Macsec                               types.Bool   `tfsdk:"macsec"`
	MacsecCipherSuite                    types.String `tfsdk:"macsec_cipher_suite"`
	MacsecFallbackCryptographicAlgorithm types.String `tfsdk:"macsec_fallback_cryptographic_algorithm"`
	MacsecFallbackKeyString              types.String `tfsdk:"macsec_fallback_key_string"`
	MacsecPrimaryCryptographicAlgorithm  types.String `tfsdk:"macsec_primary_cryptographic_algorithm"`
	MacsecPrimaryKeyString               types.String `tfsdk:"macsec_primary_key_string"`
	Mtu                                  types.Int64  `tfsdk:"mtu"`
	MtuType                              types.String `tfsdk:"mtu_type"`
	NativeVlan                           types.Int64  `tfsdk:"native_vlan"`
	NetflowOnDstInterface                types.Bool   `tfsdk:"netflow_on_dst_interface"`
	NetflowOnSrcInterface                types.Bool   `tfsdk:"netflow_on_src_interface"`
	OverrideFabricMacsec                 types.Bool   `tfsdk:"override_fabric_macsec"`
	PolicyType                           types.String `tfsdk:"policy_type"`
	PortTypeFast                         types.Bool   `tfsdk:"port_type_fast"`
	Qkd                                  types.Bool   `tfsdk:"qkd"`
	RedistribEbgpRouteMapName            types.String `tfsdk:"redistrib_ebgp_route_map_name"`
	RedistributeRouteServer              types.Bool   `tfsdk:"redistribute_route_server"`
	RouteServerRoutingTag                types.String `tfsdk:"route_server_routing_tag"`
	RoutingTag                           types.String `tfsdk:"routing_tag"`
	SkipConfigGeneration                 types.Bool   `tfsdk:"skip_config_generation"`
	Speed                                types.String `tfsdk:"speed"`
	SrcClusterName                       types.String `tfsdk:"src_cluster_name"`
	SrcEbgpAsn                           types.String `tfsdk:"src_ebgp_asn"`
	SrcFabricName                        types.String `tfsdk:"src_fabric_name"`
	SrcInterfaceConfig                   types.String `tfsdk:"src_interface_config"`
	SrcInterfaceDescription              types.String `tfsdk:"src_interface_description"`
	SrcInterfaceName                     types.String `tfsdk:"src_interface_name"`
	SrcIp                                types.String `tfsdk:"src_ip"`
	SrcIpAddress                         types.String `tfsdk:"src_ip_address"`
	SrcIpAddressMask                     types.String `tfsdk:"src_ip_address_mask"`
	SrcIpv6                              types.String `tfsdk:"src_ipv6"`
	SrcIpv6AddressMask                   types.String `tfsdk:"src_ipv6_address_mask"`
	SrcKmeServerIp                       types.String `tfsdk:"src_kme_server_ip"`
	SrcMacsecKeyChainPrefix              types.String `tfsdk:"src_macsec_key_chain_prefix"`
	SrcNetflowMonitorName                types.String `tfsdk:"src_netflow_monitor_name"`
	SrcQkdProfileName                    types.String `tfsdk:"src_qkd_profile_name"`
	SrcSwitchId                          types.String `tfsdk:"src_switch_id"`
	SrcSwitchName                        types.String `tfsdk:"src_switch_name"`
	SrcTrustpointLabel                   types.String `tfsdk:"src_trustpoint_label"`
	SrcVrfName                           types.String `tfsdk:"src_vrf_name"`
	TemplateConfigGenPeer                types.String `tfsdk:"template_config_gen_peer"`
	TemplateName                         types.String `tfsdk:"template_name"`
	TrunkAllowedVlans                    types.String `tfsdk:"trunk_allowed_vlans"`
	VrfNameNxPeerSwitch                  types.String `tfsdk:"vrf_name_nx_peer_switch"`
}
