// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_multi_cluster_connectivity_aci

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MultiClusterConnectivityAciResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the APIC cluster as reported by the controller.",
				MarkdownDescription: "The name of the APIC cluster as reported by the controller.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cluster_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The type of the cluster. The value will be auto filled as \"APIC\" for this resource.",
				MarkdownDescription: "The type of the cluster. The value will be auto filled as \"APIC\" for this resource.",
				Default:             stringdefault.StaticString("APIC"),
			},
			"enable_orchestration": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enables or disables Cisco ACI in Nexus Dashboard Orchestration on this\nACI fabric. When enabled, Nexus Dashboard can deploy tenants, networks,\nand policy configurations across multiple ACI sites. Allowed values:\n\"enabled\", \"disabled\". Note: Orchestration cannot be enabled on an ACI\nfabric that is a member of a VXLAN-ACI fabric group.\n",
				MarkdownDescription: "Enables or disables Cisco ACI in Nexus Dashboard Orchestration on this\nACI fabric. When enabled, Nexus Dashboard can deploy tenants, networks,\nand policy configurations across multiple ACI sites. Allowed values:\n\"enabled\", \"disabled\". Note: Orchestration cannot be enabled on an ACI\nfabric that is a member of a VXLAN-ACI fabric group.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("disabled"),
			},
			"enable_telemetry": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enables or disables Telemetry for the ACI fabric. Corresponds to the\n\"Enable telemetry\" checkbox in the Nexus Dashboard \"Connect Cluster\"\nworkflow. This is the equivalent of enabling the Nexus Dashboard Insights\nservice in previous releases. Allowed values: \"enabled\", \"disabled\".\n",
				MarkdownDescription: "Enables or disables Telemetry for the ACI fabric. Corresponds to the\n\"Enable telemetry\" checkbox in the Nexus Dashboard \"Connect Cluster\"\nworkflow. This is the equivalent of enabling the Nexus Dashboard Insights\nservice in previous releases. Allowed values: \"enabled\", \"disabled\".\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("disabled"),
			},
			"fabric_name": schema.StringAttribute{
				Optional:            true,
				Description:         "A unique name assigned to the ACI fabric. Corresponds to the \"Fabric Name\"\nfield in the Nexus Dashboard \"Connect Cluster\" workflow. This value is set\nonly at onboarding time and cannot be changed in place.\n",
				MarkdownDescription: "A unique name assigned to the ACI fabric. Corresponds to the \"Fabric Name\"\nfield in the Nexus Dashboard \"Connect Cluster\" workflow. This value is set\nonly at onboarding time and cannot be changed in place.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"host_name": schema.StringAttribute{
				Required:            true,
				Description:         "The IP address used to communicate with the Cisco ACI cluster. Corresponds\nto the \"Host Name/IP Address\" field in the Nexus Dashboard \"Connect Cluster\"\nworkflow. Do not include the protocol (http:// or https://) as part of the\nvalue or fabric onboarding will fail. An optional \":port\" suffix is supported.\n",
				MarkdownDescription: "The IP address used to communicate with the Cisco ACI cluster. Corresponds\nto the \"Host Name/IP Address\" field in the Nexus Dashboard \"Connect Cluster\"\nworkflow. Do not include the protocol (http:// or https://) as part of the\nvalue or fabric onboarding will fail. An optional \":port\" suffix is supported.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the terraform resource.",
				MarkdownDescription: "The unique identifier of the terraform resource.",
			},
			"latitude": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Geolocation latitude of the ACI fabric. Part of the \"Location\" selection\nshown in the Nexus Dashboard \"Connect Cluster\" workflow.\n",
				MarkdownDescription: "Geolocation latitude of the ACI fabric. Part of the \"Location\" selection\nshown in the Nexus Dashboard \"Connect Cluster\" workflow.\n",
				PlanModifiers: []planmodifier.Float64{
					float64planmodifier.UseStateForUnknown(),
				},
			},
			"license_tier": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The licensing tier to be used with this ACI fabric. Corresponds to the\n\"License tier\" field in the Nexus Dashboard \"Connect Cluster\" workflow.\nAllowed values: \"essentials\", \"advantage\", \"premier\".\n",
				MarkdownDescription: "The licensing tier to be used with this ACI fabric. Corresponds to the\n\"License tier\" field in the Nexus Dashboard \"Connect Cluster\" workflow.\nAllowed values: \"essentials\", \"advantage\", \"premier\".\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("essentials"),
			},
			"login_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "The login domain to use when authenticating with the ACI fabric.\nCorresponds to the optional \"Login Domain\" field in the Nexus Dashboard\n\"Connect Cluster\" workflow. If left empty, the fabric's local login is used.\n",
				MarkdownDescription: "The login domain to use when authenticating with the ACI fabric.\nCorresponds to the optional \"Login Domain\" field in the Nexus Dashboard\n\"Connect Cluster\" workflow. If left empty, the fabric's local login is used.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"longitude": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Geolocation longitude of the ACI fabric. Part of the \"Location\" selection\nshown in the Nexus Dashboard \"Connect Cluster\" workflow.\n",
				MarkdownDescription: "Geolocation longitude of the ACI fabric. Part of the \"Location\" selection\nshown in the Nexus Dashboard \"Connect Cluster\" workflow.\n",
				PlanModifiers: []planmodifier.Float64{
					float64planmodifier.UseStateForUnknown(),
				},
			},
			"password": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "Login password for the user name with admin privileges on the ACI fabric\nbeing added. Corresponds to the \"Password\" field in the Nexus Dashboard\n\"Connect Cluster\" workflow.\n",
				MarkdownDescription: "Login password for the user name with admin privileges on the ACI fabric\nbeing added. Corresponds to the \"Password\" field in the Nexus Dashboard\n\"Connect Cluster\" workflow.\n",
			},
			"security_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The security domain used for access control on the ACI fabric. Corresponds\nto the \"Security domain\" field in the Nexus Dashboard \"Connect Cluster\"\nworkflow. Only users with the \"all\" security domain access can add or\ndelete ACI clusters.\n",
				MarkdownDescription: "The security domain used for access control on the ACI fabric. Corresponds\nto the \"Security domain\" field in the Nexus Dashboard \"Connect Cluster\"\nworkflow. Only users with the \"all\" security domain access can add or\ndelete ACI clusters.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"telemetry_collection": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The connectivity used for telemetry collection on the ACI fabric.\nCorresponds to the \"Telemetry collection\" choice in the Nexus Dashboard\n\"Connect Cluster\" workflow. Allowed values: \"inband\" (GUI: \"In-band\") or\n\"outOfBand\" (GUI: \"Out-of-band\"). Regardless of the option chosen,\nreachability to the ACI IP address must be through the Nexus Dashboard\ndata interface. Available only when telemetry is enabled.\n",
				MarkdownDescription: "The connectivity used for telemetry collection on the ACI fabric.\nCorresponds to the \"Telemetry collection\" choice in the Nexus Dashboard\n\"Connect Cluster\" workflow. Allowed values: \"inband\" (GUI: \"In-band\") or\n\"outOfBand\" (GUI: \"Out-of-band\"). Regardless of the option chosen,\nreachability to the ACI IP address must be through the Nexus Dashboard\ndata interface. Available only when telemetry is enabled.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("inband"),
			},
			"telemetry_epg": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The APIC End Point Group (EPG) Distinguished Name (DN) used for telemetry\ncollection on the in-band management network. Required when\ntelemetry_collection is \"inband\". Available only when telemetry is enabled.\n",
				MarkdownDescription: "The APIC End Point Group (EPG) Distinguished Name (DN) used for telemetry\ncollection on the in-band management network. Required when\ntelemetry_collection is \"inband\". Available only when telemetry is enabled.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"telemetry_streaming": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The streaming protocol used for ACI telemetry. Corresponds to the\n\"Telemetry streaming\" choice in the Nexus Dashboard \"Connect Cluster\"\nworkflow. Allowed values: \"ipv4\" (GUI: \"IPv4\") or \"ipv6\" (GUI: \"IPv6\").\nAvailable only when telemetry is enabled.\n",
				MarkdownDescription: "The streaming protocol used for ACI telemetry. Corresponds to the\n\"Telemetry streaming\" choice in the Nexus Dashboard \"Connect Cluster\"\nworkflow. Allowed values: \"ipv4\" (GUI: \"IPv4\") or \"ipv6\" (GUI: \"IPv6\").\nAvailable only when telemetry is enabled.\n",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"user_name": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "Login user name with admin privileges on the ACI fabric being added.\nCorresponds to the \"User Name\" field in the Nexus Dashboard \"Connect Cluster\"\nworkflow. The credentials are used once when first establishing connectivity\nto the cluster; all subsequent communication uses provisioned secure keys.\n",
				MarkdownDescription: "Login user name with admin privileges on the ACI fabric being added.\nCorresponds to the \"User Name\" field in the Nexus Dashboard \"Connect Cluster\"\nworkflow. The credentials are used once when first establishing connectivity\nto the cluster; all subsequent communication uses provisioned secure keys.\n",
			},
			"validate_peer_certificate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allows Nexus Dashboard to verify that the certificates of hosts to which it\nconnects (such as fabric controllers) are valid and are signed by a trusted\nCertificate Authority (CA). Corresponds to the \"Validate peer certificate\"\nfield in the Nexus Dashboard \"Connect Cluster\" workflow. The certificate\nfor the fabric must already be imported into Nexus Dashboard before\nenabling this option, otherwise fabric onboarding will fail.\n",
				MarkdownDescription: "Allows Nexus Dashboard to verify that the certificates of hosts to which it\nconnects (such as fabric controllers) are valid and are signed by a trusted\nCertificate Authority (CA). Corresponds to the \"Validate peer certificate\"\nfield in the Nexus Dashboard \"Connect Cluster\" workflow. The certificate\nfor the fabric must already be imported into Nexus Dashboard before\nenabling this option, otherwise fabric onboarding will fail.\n",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(false),
			},
		},
	}
}

type MultiClusterConnectivityAciModel struct {
	ClusterName             types.String  `tfsdk:"cluster_name"`
	ClusterType             types.String  `tfsdk:"cluster_type"`
	EnableOrchestration     types.String  `tfsdk:"enable_orchestration"`
	EnableTelemetry         types.String  `tfsdk:"enable_telemetry"`
	FabricName              types.String  `tfsdk:"fabric_name"`
	HostName                types.String  `tfsdk:"host_name"`
	Id                      types.String  `tfsdk:"id"`
	Latitude                types.Float64 `tfsdk:"latitude"`
	LicenseTier             types.String  `tfsdk:"license_tier"`
	LoginDomain             types.String  `tfsdk:"login_domain"`
	Longitude               types.Float64 `tfsdk:"longitude"`
	Password                types.String  `tfsdk:"password"`
	SecurityDomain          types.String  `tfsdk:"security_domain"`
	TelemetryCollection     types.String  `tfsdk:"telemetry_collection"`
	TelemetryEpg            types.String  `tfsdk:"telemetry_epg"`
	TelemetryStreaming      types.String  `tfsdk:"telemetry_streaming"`
	UserName                types.String  `tfsdk:"user_name"`
	ValidatePeerCertificate types.Bool    `tfsdk:"validate_peer_certificate"`
}
