// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_multi_cluster_connectivity

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MultiClusterConnectivityResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the remote cluster as reported by the API",
				MarkdownDescription: "Name of the remote cluster as reported by the API",
			},
			"cluster_type": schema.StringAttribute{
				Required:            true,
				Description:         "Specify a Nexus Dashboard or APIC cluster",
				MarkdownDescription: "Specify a Nexus Dashboard or APIC cluster",
			},
			"force_remove": schema.BoolAttribute{
				Optional:            true,
				Description:         "Ensures removal will succeed in the case the remote cluster is not healthy or communicable",
				MarkdownDescription: "Ensures removal will succeed in the case the remote cluster is not healthy or communicable",
			},
			"hostname": schema.StringAttribute{
				Required:            true,
				Description:         "IP address or FQDN used to onboard the cluster. For ND clusters, using an FQDN will enable cross-launch to this cluster from other ND clusters using an FQDN.",
				MarkdownDescription: "IP address or FQDN used to onboard the cluster. For ND clusters, using an FQDN will enable cross-launch to this cluster from other ND clusters using an FQDN.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Terraform resource ID, set to the cluster name for ease of use.",
				MarkdownDescription: "Terraform resource ID, set to the cluster name for ease of use.",
			},
			"latitude": schema.Float64Attribute{
				Optional:            true,
				Description:         "Latitude in decimal degrees",
				MarkdownDescription: "Latitude in decimal degrees",
			},
			"license_tier": schema.StringAttribute{
				Optional:            true,
				Description:         "Tier of license to be used with this fabric on this cluster",
				MarkdownDescription: "Tier of license to be used with this fabric on this cluster",
			},
			"local": schema.BoolAttribute{
				Computed:            true,
				Description:         "For ND, this cluster is the local cluster. For APIC, this cluster is managed by the local cluster.",
				MarkdownDescription: "For ND, this cluster is the local cluster. For APIC, this cluster is managed by the local cluster.",
			},
			"login_domain": schema.StringAttribute{
				Optional:            true,
				Description:         "Login domain for authentication with the remote cluster",
				MarkdownDescription: "Login domain for authentication with the remote cluster",
			},
			"longitude": schema.Float64Attribute{
				Optional:            true,
				Description:         "Longitude in decimal degrees",
				MarkdownDescription: "Longitude in decimal degrees",
			},
			"multi_cluster_login_domain_name": schema.StringAttribute{
				Optional:            true,
				Description:         "When set, ND will create a login domain on the local cluster and the cluster to be registered. The new login domain will enable cross-launch between clusters without an external authentication provider.",
				MarkdownDescription: "When set, ND will create a login domain on the local cluster and the cluster to be registered. The new login domain will enable cross-launch between clusters without an external authentication provider.",
			},
			"orchestration_status": schema.StringAttribute{
				Optional:            true,
				Description:         "Desired status of the orchestration feature for APIC cluster",
				MarkdownDescription: "Desired status of the orchestration feature for APIC cluster",
			},
			"password": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "Password for authentication with the remote cluster",
				MarkdownDescription: "Password for authentication with the remote cluster",
			},
			"primary_cluster": schema.BoolAttribute{
				Computed:            true,
				Description:         "This cluster manages all connected ND or APIC clusters",
				MarkdownDescription: "This cluster manages all connected ND or APIC clusters",
			},
			"re_register": schema.BoolAttribute{
				Optional:            true,
				Description:         "Performs onboarding with the cluster again, without needing to remove the cluster",
				MarkdownDescription: "Performs onboarding with the cluster again, without needing to remove the cluster",
			},
			"security_domain": schema.StringAttribute{
				Optional:            true,
				Description:         "Security domain access for the APIC cluster",
				MarkdownDescription: "Security domain access for the APIC cluster",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				Description:         "Status of the cluster",
				MarkdownDescription: "Status of the cluster",
			},
			"telemetry_epg": schema.StringAttribute{
				Optional:            true,
				Description:         "APIC End Point Group (EPG) Distinguished Name (DN) for telemetry",
				MarkdownDescription: "APIC End Point Group (EPG) Distinguished Name (DN) for telemetry",
			},
			"telemetry_network": schema.StringAttribute{
				Optional:            true,
				Description:         "Desired connectivity for network traffic (telemetry)",
				MarkdownDescription: "Desired connectivity for network traffic (telemetry)",
			},
			"telemetry_status": schema.StringAttribute{
				Optional:            true,
				Description:         "Desired status of the telemetry feature for APIC cluster",
				MarkdownDescription: "Desired status of the telemetry feature for APIC cluster",
			},
			"telemetry_streaming_protocol": schema.StringAttribute{
				Optional:            true,
				Description:         "Telemetry Streaming Protocol",
				MarkdownDescription: "Telemetry Streaming Protocol",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "Username for authentication with the remote cluster",
				MarkdownDescription: "Username for authentication with the remote cluster",
			},
			"verify_ca": schema.BoolAttribute{
				Optional:            true,
				Description:         "Verify APIC CA using one of the trusted CAs configured on the Nexus Dashboard",
				MarkdownDescription: "Verify APIC CA using one of the trusted CAs configured on the Nexus Dashboard",
			},
			"version": schema.StringAttribute{
				Computed:            true,
				Description:         "Version of the remote cluster",
				MarkdownDescription: "Version of the remote cluster",
			},
			"virtual": schema.BoolAttribute{
				Computed:            true,
				Description:         "This is a virtual cluster",
				MarkdownDescription: "This is a virtual cluster",
			},
		},
	}
}

type MultiClusterConnectivityModel struct {
	ClusterName                 types.String  `tfsdk:"cluster_name"`
	ClusterType                 types.String  `tfsdk:"cluster_type"`
	ForceRemove                 types.Bool    `tfsdk:"force_remove"`
	Hostname                    types.String  `tfsdk:"hostname"`
	Id                          types.String  `tfsdk:"id"`
	Latitude                    types.Float64 `tfsdk:"latitude"`
	LicenseTier                 types.String  `tfsdk:"license_tier"`
	Local                       types.Bool    `tfsdk:"local"`
	LoginDomain                 types.String  `tfsdk:"login_domain"`
	Longitude                   types.Float64 `tfsdk:"longitude"`
	MultiClusterLoginDomainName types.String  `tfsdk:"multi_cluster_login_domain_name"`
	OrchestrationStatus         types.String  `tfsdk:"orchestration_status"`
	Password                    types.String  `tfsdk:"password"`
	PrimaryCluster              types.Bool    `tfsdk:"primary_cluster"`
	ReRegister                  types.Bool    `tfsdk:"re_register"`
	SecurityDomain              types.String  `tfsdk:"security_domain"`
	State                       types.String  `tfsdk:"state"`
	TelemetryEpg                types.String  `tfsdk:"telemetry_epg"`
	TelemetryNetwork            types.String  `tfsdk:"telemetry_network"`
	TelemetryStatus             types.String  `tfsdk:"telemetry_status"`
	TelemetryStreamingProtocol  types.String  `tfsdk:"telemetry_streaming_protocol"`
	Username                    types.String  `tfsdk:"username"`
	VerifyCa                    types.Bool    `tfsdk:"verify_ca"`
	Version                     types.String  `tfsdk:"version"`
	Virtual                     types.Bool    `tfsdk:"virtual"`
}
